### ISSUE TITLE
cargo install --git https://github.com/Michael-F-Bryan/mdbook-epub fail

### ISSUE THREAD

**Issue by Fulkerson** [Michael-F-Bryan/mdbook-epub#1]
Trying to build mdbook-epub with `cargo install --git https://github.com/Michael-F-Bryan/mdbook-epub` fails with on rust 1.23 stable and a current nightly.  This is the rather horrible backtrace.

    Compiling mdbook-epub v0.1.0 (https://github.com/Michael-F-Bryan/mdbook-epub#5b444da8)
    error: failed to compile `mdbook-epub v0.1.0 (https://github.com/Michael-F-Bryan/mdbook-epub#5b444da8)`, intermediate artifacts can be found at `/tmp/cargo-install.C4WymtNdieyg`

    Caused by:
    failed to run custom build command for `mdbook-epub v0.1.0 (https://github.com/Michael-F-Bryan/mdbook-epub#5b444da8)`
    process didn't exit successfully: `/tmp/cargo-install.C4WymtNdieyg/release/build/mdbook-epub-3c752ec9cfd69cb7/build-script-build` (exit code: 101)
    --- stderr
        Updating git repository `https://github.com/Michael-F-Bryan/mdbook`
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CargoError(Msg("failed to load source for a dependency on `mdbook`"), State { next_error: Some(CargoError(Msg("Unable to update https://github.com/Michael-F-Bryan/mdbook?branch=alternate_backends#95682e35"), State { next_error: Some(CargoError(Internal(Git(Error { code: -3, klass: 4, message: "revspec \'95682e35b678c0233a92813636fbe745abed9cb9\' not found" })), State { next_error: None, backtrace: Some(stack backtrace:
    0:     0x5614d4b5697c - backtrace::backtrace::trace::hba410d46ab87232a
    1:     0x5614d4b56032 - backtrace::capture::Backtrace::new::hdbe2e64f3483be34
    2:     0x5614d4b55c19 - error_chain::make_backtrace::h93dcac2a14613e38
    3:     0x5614d4b55ca4 - <error_chain::State as core::default::Default>::default::h231554e29efa3e79
    4:     0x5614d483bbcb - cargo::sources::git::utils::GitDatabase::rev_for::h6c4583f7ab879d1f
    5:     0x5614d48a0c35 - <cargo::sources::git::source::GitSource<'cfg> as cargo::core::source::Source>::update::h4653ab0b4485eb35
    6:     0x5614d4861b8a - _ZN5cargo4core8registry15PackageRegistry13ensure_loaded17h2b4179525e162ddbE.llvm.B02F815C
    7:     0x5614d4862df0 - <cargo::core::registry::PackageRegistry<'cfg> as cargo::core::registry::Registry>::query::h1aed3afdef95ffe0
    8:     0x5614d498071d - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once::hb535c4c09677b882
    9:     0x5614d4999400 - <&'a mut I as core::iter::iterator::Iterator>::next::h9f93af2c9914ce8a
    10:     0x5614d4909c0d - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h000cbd71b6902401
    11:     0x5614d498c78c - cargo::core::resolver::activate::heac4b486623a68db
    12:     0x5614d498d3d9 - cargo::core::resolver::activate_deps_loop::h2686b2ff33d99060
    13:     0x5614d49897ef - cargo::core::resolver::resolve::ha5139123f09474fe
    14:     0x5614d48f3386 - cargo::ops::resolve::resolve_with_previous::h11e89d59a073c2f8
    15:     0x5614d48f255e - cargo::ops::resolve::resolve_with_registry::h8b17509cdba1840f
    16:     0x5614d48f2365 - cargo::ops::resolve::resolve_ws::hdce30565a6810cc3
    17:     0x5614d481f383 - build_script_build::main::h7d4460492e054357
    18:     0x5614d481bab2 - std::rt::lang_start::{{closure}}::hc22b0797250aa3ef
    19:     0x5614d4b64f47 - std::rt::lang_start_internal::{{closure}}::h62834cbd79274432
                            at /checkout/src/libstd/rt.rs:59
                            - std::panicking::try::do_call::hadce92951ff7cc53
                            at /checkout/src/libstd/panicking.rs:480
    20:     0x5614d4b86c0e - __rust_maybe_catch_panic
                            at /checkout/src/libpanic_unwind/lib.rs:101
    21:     0x5614d4b6c355 - std::panicking::try::h3997a39b1b7fdce8
                            at /checkout/src/libstd/panicking.rs:459
                            - std::panic::catch_unwind::h50a0951778ee5a7c
                            at /checkout/src/libstd/panic.rs:365
                            - std::rt::lang_start_internal::hcab36a357ecdf5ab
                            at /checkout/src/libstd/rt.rs:58
    22:     0x5614d481fae3 - main
    23:     0x7fb1d1e451c0 - __libc_start_main
    24:     0x5614d481b079 - _start
    25:                0x0 - <unknown>) })), backtrace: Some(stack backtrace:
    0:     0x5614d4b5697c - backtrace::backtrace::trace::hba410d46ab87232a
    1:     0x5614d4b56032 - backtrace::capture::Backtrace::new::hdbe2e64f3483be34
    2:     0x5614d4b55c19 - error_chain::make_backtrace::h93dcac2a14613e38
    3:     0x5614d4b55ca4 - <error_chain::State as core::default::Default>::default::h231554e29efa3e79
    4:     0x5614d483bbcb - cargo::sources::git::utils::GitDatabase::rev_for::h6c4583f7ab879d1f
    5:     0x5614d48a0c35 - <cargo::sources::git::source::GitSource<'cfg> as cargo::core::source::Source>::update::h4653ab0b4485eb35
    6:     0x5614d4861b8a - _ZN5cargo4core8registry15PackageRegistry13ensure_loaded17h2b4179525e162ddbE.llvm.B02F815C
    7:     0x5614d4862df0 - <cargo::core::registry::PackageRegistry<'cfg> as cargo::core::registry::Registry>::query::h1aed3afdef95ffe0
    8:     0x5614d498071d - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once::hb535c4c09677b882
    9:     0x5614d4999400 - <&'a mut I as core::iter::iterator::Iterator>::next::h9f93af2c9914ce8a
    10:     0x5614d4909c0d - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h000cbd71b6902401
    11:     0x5614d498c78c - cargo::core::resolver::activate::heac4b486623a68db
    12:     0x5614d498d3d9 - cargo::core::resolver::activate_deps_loop::h2686b2ff33d99060
    13:     0x5614d49897ef - cargo::core::resolver::resolve::ha5139123f09474fe
    14:     0x5614d48f3386 - cargo::ops::resolve::resolve_with_previous::h11e89d59a073c2f8
    15:     0x5614d48f255e - cargo::ops::resolve::resolve_with_registry::h8b17509cdba1840f
    16:     0x5614d48f2365 - cargo::ops::resolve::resolve_ws::hdce30565a6810cc3
    17:     0x5614d481f383 - build_script_build::main::h7d4460492e054357
    18:     0x5614d481bab2 - std::rt::lang_start::{{closure}}::hc22b0797250aa3ef
    19:     0x5614d4b64f47 - std::rt::lang_start_internal::{{closure}}::h62834cbd79274432
                            at /checkout/src/libstd/rt.rs:59
                            - std::panicking::try::do_call::hadce92951ff7cc53
                            at /checkout/src/libstd/panicking.rs:480
    20:     0x5614d4b86c0e - __rust_maybe_catch_panic
                            at /checkout/src/libpanic_unwind/lib.rs:101
    21:     0x5614d4b6c355 - std::panicking::try::h3997a39b1b7fdce8
                            at /checkout/src/libstd/panicking.rs:459
                            - std::panic::catch_unwind::h50a0951778ee5a7c
                            at /checkout/src/libstd/panic.rs:365
                            - std::rt::lang_start_internal::hcab36a357ecdf5ab
                            at /checkout/src/libstd/rt.rs:58
    22:     0x5614d481fae3 - main
    23:     0x7fb1d1e451c0 - __libc_start_main
    24:     0x5614d481b079 - _start
    25:                0x0 - <unknown>) })), backtrace: Some(stack backtrace:
    0:     0x5614d4b5697c - backtrace::backtrace::trace::hba410d46ab87232a
    1:     0x5614d4b56032 - backtrace::capture::Backtrace::new::hdbe2e64f3483be34
    2:     0x5614d4b55c19 - error_chain::make_backtrace::h93dcac2a14613e38
    3:     0x5614d4b55ca4 - <error_chain::State as core::default::Default>::default::h231554e29efa3e79
    4:     0x5614d483bbcb - cargo::sources::git::utils::GitDatabase::rev_for::h6c4583f7ab879d1f
    5:     0x5614d48a0c35 - <cargo::sources::git::source::GitSource<'cfg> as cargo::core::source::Source>::update::h4653ab0b4485eb35
    6:     0x5614d4861b8a - _ZN5cargo4core8registry15PackageRegistry13ensure_loaded17h2b4179525e162ddbE.llvm.B02F815C
    7:     0x5614d4862df0 - <cargo::core::registry::PackageRegistry<'cfg> as cargo::core::registry::Registry>::query::h1aed3afdef95ffe0
    8:     0x5614d498071d - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once::hb535c4c09677b882
    9:     0x5614d4999400 - <&'a mut I as core::iter::iterator::Iterator>::next::h9f93af2c9914ce8a
    10:     0x5614d4909c0d - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h000cbd71b6902401
    11:     0x5614d498c78c - cargo::core::resolver::activate::heac4b486623a68db
    12:     0x5614d498d3d9 - cargo::core::resolver::activate_deps_loop::h2686b2ff33d99060
    13:     0x5614d49897ef - cargo::core::resolver::resolve::ha5139123f09474fe
    14:     0x5614d48f3386 - cargo::ops::resolve::resolve_with_previous::h11e89d59a073c2f8
    15:     0x5614d48f255e - cargo::ops::resolve::resolve_with_registry::h8b17509cdba1840f
    16:     0x5614d48f2365 - cargo::ops::resolve::resolve_ws::hdce30565a6810cc3
    17:     0x5614d481f383 - build_script_build::main::h7d4460492e054357
    18:     0x5614d481bab2 - std::rt::lang_start::{{closure}}::hc22b0797250aa3ef
    19:     0x5614d4b64f47 - std::rt::lang_start_internal::{{closure}}::h62834cbd79274432
                            at /checkout/src/libstd/rt.rs:59
                            - std::panicking::try::do_call::hadce92951ff7cc53
                            at /checkout/src/libstd/panicking.rs:480
    20:     0x5614d4b86c0e - __rust_maybe_catch_panic
                            at /checkout/src/libpanic_unwind/lib.rs:101
    21:     0x5614d4b6c355 - std::panicking::try::h3997a39b1b7fdce8
                            at /checkout/src/libstd/panicking.rs:459
                            - std::panic::catch_unwind::h50a0951778ee5a7c
                            at /checkout/src/libstd/panic.rs:365
                            - std::rt::lang_start_internal::hcab36a357ecdf5ab
                            at /checkout/src/libstd/rt.rs:58
    22:     0x5614d481fae3 - main
    23:     0x7fb1d1e451c0 - __libc_start_main
    24:     0x5614d481b079 - _start
    25:                0x0 - <unknown>) })', /checkout/src/libcore/result.rs:916:5
    stack backtrace:
    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
                at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1: std::sys_common::backtrace::print
                at /checkout/src/libstd/sys_common/backtrace.rs:68
                at /checkout/src/libstd/sys_common/backtrace.rs:57
    2: std::panicking::default_hook::{{closure}}
                at /checkout/src/libstd/panicking.rs:381
    3: std::panicking::default_hook
                at /checkout/src/libstd/panicking.rs:397
    4: std::panicking::rust_panic_with_hook
                at /checkout/src/libstd/panicking.rs:577
    5: std::panicking::begin_panic
                at /checkout/src/libstd/panicking.rs:538
    6: std::panicking::begin_panic_fmt
                at /checkout/src/libstd/panicking.rs:522
    7: rust_begin_unwind
                at /checkout/src/libstd/panicking.rs:498
    8: core::panicking::panic_fmt
                at /checkout/src/libcore/panicking.rs:71
    9: core::result::unwrap_failed
    10: build_script_build::main
    11: std::rt::lang_start::{{closure}}
    12: std::panicking::try::do_call
                at /checkout/src/libstd/rt.rs:59
                at /checkout/src/libstd/panicking.rs:480
    13: __rust_maybe_catch_panic
                at /checkout/src/libpanic_unwind/lib.rs:101
    14: std::rt::lang_start_internal
                at /checkout/src/libstd/panicking.rs:459
                at /checkout/src/libstd/panic.rs:365
                at /checkout/src/libstd/rt.rs:58
    15: main
    16: __libc_start_main
    17: _start

**Comment by Michael-F-Bryan** [comment]
Oops, I believe that's because I've committed the `Cargo.lock` file, meaning it'll try to check the *exact* commit I was using. Unfortunately I've done a `git rebase` on the `alternate-backends` since `Cargo.lock` was last updated, so the original commit `cargo` is looking for no longer exists!

This *should* be fixed by checking the repo out locally, manually deleting the `Cargo.lock` file and then running `cargo install`.

**Comment by Fulkerson** [comment]
That was it, thank you!

**Comment by Michael-F-Bryan** [comment]
I just merged rust-lang-nursery/mdBook#507 into `master`, so we shouldn't get this issue any more.
