### ISSUE TITLE
install break down in Windows

### ISSUE THREAD

**Issue by huangjj27** [Michael-F-Bryan/mdbook-epub#10]
I's using `rust-msvc` channel to install and haven't install CMAKE:

```
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
failed to execute command: 系统找不到指定的文件。 (os error 2)
is `cmake` not installed?

build script failed, must exit now', C:\Users\34937\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\cmake-0.1.29\src\lib.rs:632:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Michael-F-Bryan** [comment]
I'm confused... You said you haven't installed `cmake` and the error message just told you it needs `cmake` to build. Shouldn't it work if you install cmake?

**Comment by huangjj27** [comment]
I'm sorry that I havn't [search `cmake`](https://cmake.org/download/) before I open the issue. Problem solved
