### ISSUE TITLE
Indicate the process is waiting on the standard input

### ISSUE THREAD

**Issue by szabgab** [Michael-F-Bryan/mdbook-epub#102]
I ran it on https://github.com/rust-lang/book using `RUST_LOG=debug  mdbook-epub` I saw

```
[2024-05-19T20:57:17Z INFO  mdbook_epub] Booting EPUB generator...
[2024-05-19T20:57:17Z DEBUG mdbook_epub] prepared generator args = Args { standalone: false, root: "." }
[2024-05-19T20:57:17Z DEBUG mdbook_epub] run EPUB book build...
Running mdbook-epub as plugin...
```

but I did not have the patience to see any more output.

It took me a while, and reading the source code to understand that it was waiting on the standard input.

Maybe this last line should indicate that for the confused users like myself.

**Comment by szabgab** [comment]
It took me a while, and reading the source code to understand that it was waiting on the standard input.

**Comment by blandger** [comment]
I will update the message to make it more clear.

**Comment by szabgab** [comment]
Thanks. A suggestion: 
`Running mdbook-epub as plugin waiting on the STDIN. If you wanted to process the files in the current folder, use the -s flag`

**Comment by blandger** [comment]
Sure

**Comment by blandger** [comment]
Fixed
