### ISSUE TITLE
cargo audit is failing

### ISSUE THREAD

**Issue by szabgab** [Michael-F-Bryan/mdbook-epub#109]
See [report](https://github.com/szabgab/mdbook-epub/actions/runs/9153773962)

**Comment by dieterplex** [comment]
Major vulnerability and yanked deps has been fixed in recent update (0.4.40). Could you verify that?

For `ansi_term`(unmaintained) & `atty`(unsound) warnings, maybe migrate `structopt` to `getopts` or `clap-derive`.

**Comment by blandger** [comment]
StrustOpt is replaced by clap
