### ISSUE TITLE
Using the crate

### ISSUE THREAD

**Issue by szabgab** [Michael-F-Bryan/mdbook-epub#113]
I wanted to thank to the all the people involved for creating and maintaining this crate.

Using it I created a web site where people can download epub version of some of the Rust-related books.

There are a number of issues with the books that I'll have to handle and / or report, but I am quite satisfied with this first version.

https://rust-ebooks.code-maven.com/

**Comment by blandger** [comment]
You can find more rust books in my repo

https://github.com/blandger/epub-rust-books
