### ISSUE TITLE
Please provide a configuration to name the output file

### ISSUE THREAD

**Issue by NuLL3rr0r** [Michael-F-Bryan/mdbook-epub#116]
Although the project outputs the book title as a file name it would be nice to have control over how the file name is generated (for example we might avoid whitespace in the name for obvious reasons).

mdbook-typst has this like:

```
[output.typst.output]
format = "pdf"
name = "the-senseglove-unreal-engine-handbook.pdf"
```

**Comment by blandger** [comment]
We have a request to add output file name with path.
I'm not sure if we want to separate 'out put path' from 'file name' or make one param like 'output path with file name'.
So I'm closing this duplicate.

https://github.com/Michael-F-Bryan/mdbook-epub/issues/112
