### ISSUE TITLE
Replace StructOpt lib by latest clap version.

### ISSUE THREAD

**Issue by blandger** [Michael-F-Bryan/mdbook-epub#117]
I've started that task.
After this is finished we'll be able to continue with issue - https://github.com/Michael-F-Bryan/mdbook-epub/issues/112

**Comment by dieterplex** [comment]
I've done this before (https://github.com/dieterplex/mdbook-epub/commit/81b1e7184b04a731623baf06bca06fee9d6b7ef2), but may be outdated a bit.

**Comment by blandger** [comment]
Ok, make an code update and create PR
