### ISSUE TITLE
corrupt

### ISSUE THREAD

**Issue by emilhwn** [Michael-F-Bryan/mdbook-epub#20]
Building on arch linux and macOS results in corrupt .epub.
[llpp](https://wiki.archlinux.org/index.php/Llpp) _renders_ the .epub but only the page headers show.

**Comment by Michael-F-Bryan** [comment]
Can you provide something I can use to reproduce this issue? Also, do you have an example of the generated EPUB file I can look at.

**Comment by lmarlow** [comment]
I was able to reproduce this in Apple's Books.app with `mdbook init` and `mdbook-epub --standalone` this morning. Calibre's ebook-viewer can read it, though. Attached is the gzipped version that Books.app says is corrupt.

[Test mdbook-epub.epub.gz](https://github.com/Michael-F-Bryan/mdbook-epub/files/3257916/Test.mdbook-epub.epub.gz)

**Comment by justacec** [comment]
I am having the same issue after installing this today.

**Comment by hoodie** [comment]
issue persists

**Comment by blandger** [comment]
> to be a bit more helpful, I was trying to epubify these books
> https://github.com/cfsamson/book-exploring-async-basics
> https://github.com/cfsamson/books-futures-explained
> maybe there is something in there that makes them unpalatable for mdbook-epub??

I tried to build both books with latest changes which are in PRs for now. I was able to build both successfully with little tweaks in book.toml. Styles are quite ugly now. Embedded youtube videos trigger opening system browser with linked video (on Linux).
Embedded mp4 video is not quite shown in book (I don't know if something is missing, JS or else?).

**Comment by blandger** [comment]
@hoodie 
as part of testing my code I've create epub for you book. take it here:
https://github.com/blandger/books-futures-explained/releases/tag/0.0.1

**Comment by blandger** [comment]
One more book check
https://github.com/blandger/book-exploring-async-basics/releases/tag/0.0.1

**Comment by blandger** [comment]
should be fixed by new 0.5.0 version
https://docs.rs/epub-builder/0.5.0/epub_builder/
