### ISSUE TITLE
markdown tables do not render as tables

### ISSUE THREAD

**Issue by dougrich** [Michael-F-Bryan/mdbook-epub#24]
__Reduction file:__
```
# Chapter 1

|test|test2|
|----|-----|
|cool|neato|
```

__Expected:__

The epub renderer renders tables mostly consistently with the HTML one, which looks something like this:
![screenshot-localhost_3000-2019 12 07-19_38_11](https://user-images.githubusercontent.com/10737526/70383819-226ace80-1929-11ea-8cf8-901e440b4ea5.png)

__Actual:__

The epub renderer outputs the plain text with no processing. Something like this:

```
|test|test2| |----|-----| |cool|neato|
```

__Additional Information:__
- manually putting in `table` tags instead _does_ correctly render tables, so I suspect this is just turning on additional preprocessor
- I'm using Calibre on linux as the reader for testing
- I'd be open to submitting code if you can point me in the direction of it (and will forgive a novice rust programmer)

**Comment by blandger** [comment]
That issue can be fixed by using more advanced 'pulldown-cmark' parser: like
```
    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_FOOTNOTES);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_TASKLISTS);
    let pulldown_parser = Parser::new_ext(src, options);
```

I've tested it works correctly for TRPL epub book generation in my branch:
https://github.com/Michael-F-Bryan/mdbook-epub/compare/master...blandger:add_links_preprocessing

**Comment by blandger** [comment]
fixed in master
