### ISSUE TITLE
[Feature Request] Configure language in EPUB metadata

### ISSUE THREAD

**Issue by glatavento** [Michael-F-Bryan/mdbook-epub#47]
Firstly, many thanks to your efforts. 

It seems that mdbook-epub set "en" as default language in EPUB metadata:
https://github.com/Michael-F-Bryan/mdbook-epub/blob/4646d677a110d22cf0560f733c4def8a86c8d416/src/generator.rs#L64
I found there is a language field in mdbook's `book.toml` (see [general.md](https://github.com/rust-lang/mdBook/blob/master/guide/src/format/configuration/general.md#general-metadata)), how about writing this option to generated EPUB? This will save a lot of effort for non-English users.

Best regards.

**Comment by blandger** [comment]
That option goes from mdbook, see here :
https://github.com/rust-lang/mdBook/blob/336640633b1741de644e971a1a2cd8b30c595368/src/config.rs#L419
If I'm not mistaken you can specify it in 'book.toml' file.

I've used such 'lang value' in my fork code for appending it's value as part of output 'epub file name'.
See here:
https://github.com/blandger/mdbook-epub/blob/3e9e66e1a836afa7648095653c7bf16212e20c6f/src/lib.rs#L132

**Comment by glatavento** [comment]
Sorry for my clumsy expression, I found EPUB itself already contains language data (see [dc:language](https://www.w3.org/publishing/epub3/epub-packages.html#sec-opf-dclanguage), or check `content.opf` in epub file), and change this
https://github.com/Michael-F-Bryan/mdbook-epub/blob/4646d677a110d22cf0560f733c4def8a86c8d416/src/generator.rs#L64
to this
```
if let Some(lang) = self.ctx.config.book.language.clone() {
    self.builder.metadata("lang", lang)?;
} else {
    self.builder.metadata("lang", "en")?;
}
```
can write language value (specified in `book.toml`) to EPUB's metadata. I tried this and it works well, so I'll make a PR; but I'm not a rust expert (nor a EPUB expert), so please correct me if I didn't get it right.

**Comment by blandger** [comment]
Seems correct, go ahead pls.
