### ISSUE TITLE
mdbook-epub finishes but resulting epub seems empty (although all content is in there).

### ISSUE THREAD

**Issue by spaetz** [Michael-F-Bryan/mdbook-epub#59]
The mdbook at https://gitlab.com/sspaeth/survival-manual (viewable as online mdbook at https://sspaeth.gitlab.io/survival-manual
seems to be successfully parsed by mdbook-epub -s and a resulting epub file is created (attached, just renamed the .epub to .zip otherwise github refuses to upload it). However, when I load it in fbreader, or any other epub viewer, it seems either empty or leads to infinite spinners. So something seems wrong with the epub file.
I know too little about the epub structure to be able to know what went wrong there.

rename back to .epub:
[SurvivalManual.zip](https://github.com/Michael-F-Bryan/mdbook-epub/files/9122136/SurvivalManual.zip)
.

**Comment by dieterplex** [comment]
Check with [epubcheck](https://github.com/w3c/epubcheck) tool and compare the zip, epub is a plain zip file, with the one generated from mdbook-epub by my self.
I found that HTMLs extracted from your epub file are not identical to the one generated from mkbook-epub. They are not well-formed HTMLs, no root _html_ tag, and tables are not converted.

How do you create the epub file?

**Comment by spaetz** [comment]
Thanks for the link to epubcheck, will use it for sure. The online mdbook comes from mdbook 4.20, the epub was created using whatever cargo install mdbook-epub provides me with (using the -s standalone) command line option.

**Comment by dieterplex** [comment]
Cargo would install pretty old version, v0.3.0, of mdbook-epub by default. 
Since I'm using v0.4.15-beta and fine, maybe it's the root cause. Would you give it a try for newer version?

```
cargo install --version 0.4.15-beta mdbook-epub
```

**Comment by spaetz** [comment]
OK, attached is the epub being produced by mdbook-epub 0.4.15-beta (I ran it in --standalone mode) (renamed to .zip again to enable github upload)
[Survival Manual.zip](https://github.com/Michael-F-Bryan/mdbook-epub/files/9128285/Survival.Manual.zip)

fbreader is still showing an empty document, so something is still not right, but epubcheck is *only* emitting two errors:

```
ERROR(RSC-005): Survival Manual.epub/OEBPS/content.opf(-1,-1): Error while parsing file: The entity name must immediately follow the '&' in the entity reference.
ERROR(OPF-001): Survival Manual.epub/OEBPS/content.opf(-1,-1): There was an error when parsing the EPUB version: Version not found.

Check finished with errors
Messages: 0 fatals / 2 errors / 0 warnings / 0 infos

EPUBCheck completed

```
.

**Comment by spaetz** [comment]
Oii, I removed the ampersand from the authors ("US Army & contributors") and now, epubcheck starts becoming very verbose....
epubcheck log is attached
[err.log](https://github.com/Michael-F-Bryan/mdbook-epub/files/9128308/err.log)
.

**Comment by dieterplex** [comment]
mdbook-epub depends on epub-builder to create book but is still using epub2 format instead, so that figcaption and webp is not support yet when checking with epub 2.0.1.
Though it seems that figures are rendered fine with calibre's ebook-viewer. Maybe fbreader follow the spec strictly?

**Comment by spaetz** [comment]
Ok, so closing this one as it works with a newer mdbook-epub. Perhaps we should protect against an ampersand in the author's list though?
