### ISSUE TITLE
Internal relative links not work

### ISSUE THREAD

**Issue by theowenyoung** [Michael-F-Bryan/mdbook-epub#62]
Hi, Thanks for the great tool!

It seems internal link not works,  for example:

```
[A](./a.md)
```

and I found @dieterplex forked branch <https://github.com/dieterplex/mdbook-epub/tree/fix-local-md-link> can work fine.

@dieterplex would you like merge it to upstream?

**Comment by dieterplex** [comment]
Context: https://github.com/rust-lang/mdBook/issues/431
So I left #53 closed sometimes ago. :smiley:

**Comment by theowenyoung** [comment]
Thanks I see.
