### ISSUE TITLE
error[E0597]: `local_ctx` does not live long enough

### ISSUE THREAD

**Issue by niaiwomattt** [Michael-F-Bryan/mdbook-epub#63]
```bash
error[E0597]: `local_ctx` does not live long enough
   --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/mdbook-0.3.7/src/renderer/html_handlebars/helpers/navigation.rs:155:25
    |
155 |             t.render(r, &local_ctx, &mut local_rc, out)
    |                         ^^^^^^^^^^ borrowed value does not live long enough
156 |         })?;
    |         -
    |         |
    |         `local_ctx` dropped here while still borrowed
    |         borrow might be used here, when `local_rc` is dropped and runs the destructor for type `handlebars::RenderContext<'_, '_>`
    |
    = note: values in a scope are dropped in the opposite order they are defined

For more information about this error, try `rustc --explain E0597`.
error: could not compile `mdbook` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mdbook-epub v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installeVRNpc`

```

**Comment by blandger** [comment]
Pls give more details. Rust compiler version, platform, that is the branch ? Thanks.

**Comment by niaiwomattt** [comment]
rustc 1.65.0 (897e37553 2022-11-02)
cargo 1.65.0 (4bc8f24d3 2022-10-20)
macOS 10.14.6

command: cargo install mdbook-epub

**Comment by dieterplex** [comment]
I believe it's https://github.com/rust-lang/rust/issues/99591.
Before releasing next version, consider to install with

```
cargo install --git https://github.com/Michael-F-Bryan/mdbook-epub
```

**Comment by niaiwomattt** [comment]
> I believe it's [rust-lang/rust#99591](https://github.com/rust-lang/rust/issues/99591). Before releasing next version, consider to install with
> 
> ```
> cargo install --git https://github.com/Michael-F-Bryan/mdbook-epub
> ```

Thank you. After installing `nightly-x86_64-unknown-linux-gnu installed - rustc 1.67.0-nightly (1eb62b123 2022-11-27)` version, I successfully installed `cargo install --git https://github.com/Michael-F-Bryan/mdbook-epub` using the command you provided

**Comment by blandger** [comment]
New updated version 0.4.25 is published on [crates.io](https://crates.io/crates/mdbook-epub/0.4.25).
