### ISSUE TITLE
Thoughts about migrating to Github Actions

### ISSUE THREAD

**Issue by dieterplex** [Michael-F-Bryan/mdbook-epub#71]
Recently I found travis-ci build status badge in README is missing. The link of the badge is no longer valid and seems  moved to <https://app.travis-ci.com/github/Michael-F-Bryan/mdbook-epub> long time ago. Last build in that page is 2 years ago and the banner urge you to update the price plan. If we are going to keep useing travis-ci, I guess we need to request [Travis CI OSS plan](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source) by @Michael-F-Bryan. Then there will be credits per month could be used. Or we should consider other better free lunch.

In my mind, one is AppVeyor currently used and the popular one, Github Actions. But I'm not familiar with AppVeyor to comment its pros & cons. Currently CI with AppVeyor only run on Windows platform that could be a point to improve . I do think there would be more contributors familiar to Github Actions and have better support for processes like binary releasing and crates.io publishing in place. If it is a low hanging fruit, why don't we move forward?

**Comment by blandger** [comment]
Added simple GH action script that can be improved later.
