### ISSUE TITLE
tag sub and sup should not be reset in css

### ISSUE THREAD

**Issue by simsilver** [Michael-F-Bryan/mdbook-epub#72]
https://github.com/Michael-F-Bryan/mdbook-epub/blob/9f2a369723a320e029b786e856151a4c1890d279/src/master.css#L47-L48

`2<sup>n-1</sup>` will be shown as 2n-1 instead of 2^(n-1) when reset, which seems a mistake.

**Comment by blandger** [comment]
You are right. I'll fix it in a next release.

**Comment by blandger** [comment]
Fixed in 0.4.31
