### ISSUE TITLE
New Lines removed in Code Blocks

### ISSUE THREAD

**Issue by tahir-hassan** [Michael-F-Bryan/mdbook-epub#94]
I have a file in which I have PowerShell code blocks like so:

<pre>
```powershell
if (Test-Path "myproject.zip") {
    del "myproject.zip";
}
& "c:\Program Files\7-Zip\7z.exe" a myproject.zip .\myproject\ "-xr!.git" "-xr!.gitignore"
pause
```
</pre>

But it looks like so when it is outputted to epub:

<pre>
if (Test-Path "myproject.zip") { del "myproject.zip"; }
& "c:\Program Files\7-Zip\7z.exe" a myproject.zip .
\myproject\ "-xr!.git" "-xr!.gitignore" pause
</pre>

Is there a reason for this, or should I be using some other means of including code?

Thank you,
Tahir

**Comment by blandger** [comment]
@tahir-hassan if there is something I can help you with?
I'm going to close issue.

**Comment by tahir-hassan** [comment]
> @tahir-hassan if there is something I can help you with?
> I'm going to close issue. 

For now yes please.  The thing is, I am using SumatraPDF on Windows so there might be some sort of difference to Linux. Without me trying it on Linux and reproducing it, it isn't really something that anyone can work on (for now).
