### ISSUE TITLE
downloading remote resource with parametrized url can't contain Chinese

### ISSUE THREAD

**Issue by Initsnow** [Michael-F-Bryan/mdbook-epub#96]
[log.log](https://github.com/Michael-F-Bryan/mdbook-epub/files/14800757/log.log)

**Comment by blandger** [comment]
Could you pls check an update using branch
https://github.com/blandger/mdbook-epub/tree/fix_non_ascii_char_in_remote_url
Thanks

**Comment by Initsnow** [comment]
> Could you pls check an update using branch https://github.com/blandger/mdbook-epub/tree/fix_non_ascii_char_in_remote_url Thanks

It works well now, thanks for the effort
